	.ORIG x3000
	
	LEA R0 , INPUT
	LD R1 , TEMP1
	ADD R0 , R0 , #-1
	ADD R1 , R1 , #-1
	ADD R7 , R7 , #-2

READIN	ADD R0 , R0 , #1	;PLACES THE VALUES IN INPUT INTO X3100 IN ORDER	
	ADD R1 , R1 , #1
	ADD R7 , R7 , #1	;R7 WILL COUNT STRING LENGTH AND IS USED LATER FOR 
	LDR R2 , R0 , #0	;HOW MANY COMPARISONS TAKE PLACE
	STR R2 , R1 , #0
	BRz REVERSE
	BR READIN
		
REVERSE	LEA R0 , INPUT 		;PLACES VALUES IN INPUT INTO X3200 IN REVERSE ORDER
	LD R1 , TEMP2
	ADD R1 , R1 , R7
	ADD R0 , R0 , #-1
	ADD R1 , R1 , #1

READIN2	ADD R0 , R0 , #1
	ADD R1 , R1 , #-1
	LDR R2 , R0 , #0
	STR R2 , R1 , #0
	BRz CHECK
	BR READIN2

CHECK	ADD R7 , R7 , #1
	LD R0 , TEMP1
	LD R1 , TEMP2
	ADD R0 , R0 , #-1
	ADD R1 , R1 , #-1

CLOOP	ADD R7 , R7 , #-1	;CHECKS VALUES FROM LIST1 TO LIST2 (REVERSE LIST)
	BRz YES			;ENDS IF THEY ARE NOT EQUAL
	ADD R0 , R0 , #1  
	ADD R1 , R1 , #1
	LDR R2 , R0 , #0
	LDR R3 , R1 , #0
	NOT R2 , R2 
	ADD R2 , R2 , #1
	ADD R2 , R2 , R3
	BRz CLOOP
	BR NO

NO	ADD R5 , R5 , #-1	;BRANCHES HERE IF A SINGLE VALUE DOES NOT MATCH THE RESPECTIVE ONE
	ST R5 , ANS		;IN THE REVERSED LIST
	BR END

YES	ADD R5 , R5 , #1	;BRANCHES HERE IF ALL VALUES MATCH AND ALL VALUES HAVE BEEN TESTED
	ST R5 , ANS
	BR END

END	HALT

INPUT 	.STRINGZ "RACECAR"
TEMP1	.FILL x3100
TEMP2	.FILL x3200
ANS 	.BLKW 0

	.END
