	.ORIG x3000
	
	LD R7 , MASK
	LD R0 , START
LOOP	LDR R1 , R0 , #0
	ADD R0 , R0 , #1
	
	ADD R1 , R1 , #0	;CHECK TO SEE IF THE NEXT IN THE LIST IS EMPTY
	BRz END
	
	AND R1 , R1 , R7	;AND WITH MASK TO SEE IF POS
	BRz LOOP
	
	ADD R5 , R5 , #1	;NOT ZERO AND NOT POS = NEG
	BR LOOP 
	

END	HALT

START	.FILL x3030
MASK	.FILL x8000
	.END